{
  "quotes": [
    "HEY, I'M GUY FIERI,\r\n  AND WE'RE ROLLING OUT,\r\n\r\n",
    "LOOKING FOR AMERICA'S GREATEST\r\n DINERS, DRIVE-INS AND DIVES.\r\n\r\n",
    "<i> THIS TRIP...</i>\r\n<i> TOTALLY FRIED.</i>\r\n\r\n",
    "THAT'S FRENCH\r\n FRY-TASTIC.\r\n\r\n",
    "<i> AT A 50-YEAR-OLD DINER</i>\r\n  <i> IN PHILADELPHIA,</i>\r\n\r\n",
    "<i> WHERE A FRENCH-TRAINED CHEF</i>\r\n <i> IS FRYING UP HIS OWN TAKE</i>\r\n\r\n",
    "<i> ON DINER COOKING...</i>\r\n\r\n",
    "TASTE THE DUCK?\r\n       TASTY.\r\n\r\n",
    "NOT WHAT YOU'D EXPECT\r\n   AT A DINER.\r\n\r\n",
    "<i> AND A CLASSIC</i>\r\n  <i> CALIFORNIA DRIVE-IN...</i>\r\n\r\n",
    "NEXT, PLEASE.\r\n\r\n",
    "<i> THAT'S KNOCKIN' 'EM DEAD</i>\r\n <i> WITH DEEP-FRIED FALAFEL...</i>\r\n\r\n",
    "CALIFORNIA FUSION.\r\n\r\n",
    "THIS IS FANTASTIC\r\n     FALAFEL.\r\n\r\n",
    "<i> AND A SMALL-TOWN CAFé</i>\r\n <i> ON THE EDGE OF THE DESERT...</i>\r\n\r\n",
    "HERE YOU GO.\r\n      THANK YOU.\r\n\r\n",
    "<i> WHERE THEY'RE DOING A FRENCH</i>\r\n <i> CLASSIC THE DEEP-FRIED WAY.</i>\r\n\r\n",
    "I DON'T THINK I'VE EVER SEEN\r\n CHICKEN CORDON BLEU SUBMERGED.\r\n\r\n",
    "IT DEFINITELY\r\n    IS THE CRUNCHIEST.\r\n\r\n",
    "I MEAN, THAT HAS\r\n    A TEXTURE ON THAT.\r\n\r\n",
    "THAT'S ALL RIGHT HERE RIGHT NOW\r\nON \"DINERS, DRIVE-IN AND DIVES.\"\r\n\r\n",
    "Closed Captions provided\r\n by Scripps Networks, LLC.\r\n\r\n",
    "Captioned by\r\nClosed Captioning Services, Inc.\r\n\r\n",
    "ON THIS LEG OF OUR\r\n  TOTALLY FRIED TRIP,\r\n\r\n",
    "WE'RE IN PHILADELPHIA.\r\n\r\n",
    "NOW WE'RE NOT HERE\r\n TO TALK ABOUT CHEESESTEAKS.\r\n\r\n",
    "WE'RE HERE TO MEET\r\n  A FRENCH-TRAINED CHEF\r\n\r\n",
    "WHO'S PUTTING A WHOLE NEW SPIN\r\n  ON DINER FRIED FARE.\r\n\r\n",
    "IT'S FANTASTIC.\r\n\r\n",
    "THAT IS BEAUTIFUL.\r\n\r\n",
    "NOT WHAT YOU WOULD\r\n  EXPECT AT A DINER.\r\n\r\n",
    "WHAT DO YOU THINK?\r\n  IT'S AWESOME.\r\n\r\n",
    "DELICIOUS.\r\n     AMAZING.\r\n  THE BEST.\r\n\r\n",
    "<i> CHECK OUT THE PULLED-PORK</i>\r\n   <i> EMPANADAS,</i>\r\n\r\n",
    "<i> SPRING ROLLS MADE</i>\r\n <i> WITH HOMEMADE DUCK CONFIT,</i>\r\n\r\n",
    "<i> SHRIMP-AND-CRAB POT STICKERS</i>\r\n <i> AND FRIED OYSTER SALAD.</i>\r\n\r\n",
    "IT'S A DINER,\r\n BUT IT'S NOT DINER FOOD.\r\n\r\n",
    "<i> EVEN THE FRIES</i>\r\n <i> ARE SOMETHING SPECIAL...</i>\r\n\r\n",
    "THEY MELT\r\n IN YOUR MOUTH.\r\n\r\n",
    "<i> HAND CUT AND FRIED TWICE</i>\r\n\r\n",
    "<i> FOR STEAK FRITES,</i>\r\n <i> THE WAY THEY DO IT IN PARIS.</i>\r\n\r\n",
    "I LOVE THE FRENCH.\r\nI LOVE THE FRENCH,\r\n TOO, BROTHER.\r\n\r\n",
    "I WOULDN'T HAVE THE FRENCH FRIES\r\n IF IT WEREN'T FOR THE FRENCH,\r\n\r\n",
    "RIGHT?\r\nYOU WOULDN'T\r\nHAVE A CAREER\r\n\r\n",
    "IF IT WASN'T\r\nFOR LIVING IN FRANCE.\r\n     THIS IS TRUE.\r\n\r\n",
    "<i> AND AFTER COOKING</i>\r\n  <i> SCHOOL IN PARIS,</i>\r\n\r\n",
    "<i> PETER'S CAREER'S</i>\r\n  <i> BACK HOME IN PHILLY</i>\r\n\r\n",
    "<i> AT THE 50-YEAR-OLD</i>\r\n  <i> SILK CITY DINER,</i>\r\n\r\n",
    "<i> WHICH HAS BEEN</i>\r\n  <i> TOTALLY REVAMPED</i>\r\n\r\n",
    "<i>BY FARMER-TURNED-RESTAURATEUR</i>\r\n<i>MARK BEE--A LIFELONG FOODIE...</i>\r\n\r\n",
    "THAT'S BEAUTIFUL.\r\n\r\n",
    "<i> WHO COULDN'T RESIST WHEN</i>\r\n <i> THIS NEIGHBORHOOD LANDMARK</i>\r\n\r\n",
    "<i> WENT UP FOR SALE.</i>\r\n\r\n",
    "I USED TO DO THE PLUMBING HERE.\r\n\r\n",
    "AND AFTER WORKING\r\n    IN RESTAURANTS,\r\n\r\n",
    "YOU WANTED TO BECOME\r\n    A RESTAURANT DUDE?\r\nI DO. I LOVE IT.\r\n I LOVE IT.\r\n\r\n",
    "<i> SO HE RENOVATED IT HIS WAY...</i>\r\n\r\n",
    "I JUST DON'T WANT IT TO BE\r\n  LIKE EVERY OTHER PLACE.\r\n\r\n",
    "IT'S WHAT I LIKE.\r\n\r\n",
    "<i> AND BROUGHT IN PETER</i>\r\n  <i> TO REDO THE MENU.</i>\r\n\r\n",
    "HE'S AWESOME. I JUST\r\nLET HIM DO THIS THING.\r\n\r\n",
    "I JUST MAKE FOOD\r\n I LIKE TO EAT, YOU KNOW?\r\n\r\n",
    "IT'S LIKE IF I LIKE TO EAT IT--\r\n\r\n",
    "I THINK MOST PEOPLE LIKE TO EAT\r\n  WHAT I LIKE TO EAT.\r\n\r\n",
    "<i> ...LIKE THOSE TOTALLY</i>\r\n  <i> HOMEMADE EMPANADAS.</i>\r\n\r\n",
    "THIS IS JUST LIKE MY<i> ABUELITA--</i>\r\n MY GRANDMOTHER--FANTASTIC.\r\n\r\n",
    "IT TASTES\r\n  JUST LIKE HOME COOKIN'.\r\n\r\n",
    "<i> IT STARTS WITH A FRESH HAM.</i>\r\n\r\n",
    "YOU DON'T\r\nUSE SHOULDER?\r\n    NO, I WAS ALWAYS\r\n    MORE OF A LEG MAN\r\n\r\n",
    "THAN A SHOULDER MAN,\r\n     YOU KNOW?\r\n HEY, HONEY,\r\nNICE SHOULDER.\r\n\r\n",
    "SO WE'RE JUST GONNA,\r\n    LIKE, CUT THIS UP\r\n\r\n",
    "AND JUST TOSS 'EM\r\n     IN THERE.\r\n\r\n",
    "CHILI POWDER.\r\n      GO FOR IT,\r\n      YOU KNOW?\r\n\r\n",
    "THAT MUCH.\r\n I LOVE THAT.\r\nOH, SO THAT MUCH.\r\n\r\n",
    "SMOKED PAPRIKA\r\n   AND CHIPOTLE POWDER.\r\n\r\n",
    "YOU CAN DUMP IT\r\n     ALL IN THERE.\r\nLET'S GET WILD.\r\n\r\n",
    "YEAH, YOU KNOW?\r\nWHEN DO WE START\r\n DRINKING BEER?\r\n\r\n",
    "UH, WELL,\r\n   PRETTY SOON, I HOPE.\r\n\r\n",
    "<i> AFTER FINISHING UP WITH ONION,</i>\r\n  <i> GARLIC AND CUMIN,</i>\r\n\r\n",
    "<i> PETER SIMMERS THE HAM TILL IT</i>\r\n <i> PRETTY MUCH FALLS APART.</i>\r\n\r\n",
    "HAND SHRED\r\nOR FORK SHRED?\r\n     UH, FORK, HAND,\r\n     YOU KNOW?\r\n\r\n",
    "IF YOU CAN GET YOUR FOOT UP\r\nAROUND THERE WITH SOME YOGA,\r\n\r\n",
    "GET INTO IT.\r\n     THERE YOU GO.\r\n\r\n",
    "<i> HE MIXES IT UP</i>\r\n <i> WITH SWEET POTATO, CILANTRO,</i>\r\n\r\n",
    "<i> CINNAMON AND BLACK BEANS.</i>\r\n\r\n",
    "THAT'S TASTY.\r\n      I THINK\r\n     IT'S ALL RIGHT.\r\n\r\n",
    "I COULD JUST MAKE THAT INTO,\r\n LIKE, A--LIKE, A BALL.\r\n       YEAH.\r\n\r\n",
    "DEEP-FRY IT.\r\n I WOULD JUST\r\nWALK AROUND WITH IT.\r\n\r\n",
    "<i> INSTEAD, WE'LL ROLL OUT</i>\r\n  <i> SOME FRESH DOUGH.</i>\r\n\r\n",
    "SO WE GOT\r\n    OUR LITTLE SKINS.\r\n\r\n",
    "<i> FILL IT...</i>\r\n\r\n",
    "AND THAT'S IT.\r\n\r\n",
    "<i> FOLD IT...</i>\r\n\r\n",
    "ALL DONE.\r\n\r\n",
    "<i> AND FRY IT.</i>\r\n\r\n",
    "HOW LONG\r\nDO THOSE TAKE?\r\n   THREE TO FIVE MINUTES.\r\n\r\n",
    "<i> THEY'LL BE SERVED</i>\r\n <i> WITH A CHIPOTLE-HONEY GLAZE,</i>\r\n\r\n",
    "<i> PINEAPPLE-HOT PEPPER SALSA</i>\r\n\r\n",
    "<i> AND CILANTRO, RED ONION</i>\r\n <i> AND LIME ZEST SOUR CREAM.</i>\r\n\r\n",
    "OH, THAT LOOKS\r\n     OUTSTANDING.\r\n\r\n",
    "WOW. THAT IS AN ORCHESTRA\r\n    RIGHT THERE.\r\n\r\n",
    "THAT'S A MELODY\r\n   OF JUST GREAT FLAVOR.\r\nAWESOME.\r\n\r\n",
    "<i> AND AFTER THIS LATIN FAVOR,</i>\r\n\r\n",
    "<i> PETER'S CRANKIN' OUT</i>\r\n <i> SOME ASIAN SPECIALTIES,</i>\r\n\r\n",
    "<i> LIKE SHRIMP-AND-CRAB</i>\r\n   <i> POT STICKERS.</i>\r\n\r\n",
    "SACRE BLEU.\r\n\r\n",
    "SO THIS IS PAN-FRY\r\n    AT ITS GREATEST.\r\n\r\n",
    "AND LOOK HOW FAST WE'RE\r\n  PUTTIN' A CRUST ON THAT.\r\n\r\n",
    "I SEE HOT COMING.\r\n\r\n",
    "WE GOT THE CRAB,\r\n THE SHRIMP.\r\n\r\n",
    "REALLY, YOU GET THE TEXTURE\r\n OF THE SHRIMP BACK.\r\n\r\n",
    "IT DIDN'T\r\nGO TOO FAR.\r\n\r\n",
    "YOU HAVE SOME OF THE GINGER\r\n RIGHT OFF THE BAT.\r\n\r\n",
    "THAT'S FRENCH\r\n FRY-TASTIC.\r\n\r\n",
    "<i> AND GET A LOAD</i>\r\n  <i> OF THE SPRING ROLLS</i>\r\n\r\n",
    "<i> FILLED WITH A FRENCH</i>\r\n  <i> CLASSIC--DUCK CONFIT.</i>\r\n\r\n",
    "OH, THE DUCK--WE JUST\r\n  SALT IT WITH A LITTLE SALT,\r\n\r\n",
    "SUGAR, FIVE SPICE--\r\n   CHINESE FIVE SPICE--\r\n\r\n",
    "STAR ANISE,\r\n      CINNAMON.\r\nLIKE BUTTAH.\r\n\r\n",
    "IT'S A HEART ATTACK\r\n     IN A BOWL.\r\n YEAH, NOTHING\r\nWRONG WITH THAT.\r\n\r\n",
    "YOU'RE THE CHEF,\r\nNOT THEIR DOCTOR.\r\n      EXACTLY.\r\n\r\n",
    "SAUTéED ONIONS,\r\nCABBAGE, PORTOBELLOS,\r\n\r\n",
    "CARROTS, SOME GINGER,\r\n A LITTLE HOISIN--\r\n\r\n",
    "KIND OF LIKE A LITTLE ASIAN\r\n BARBECUE SAUCE OF SORTS.\r\n   LIKE CHINESE KETCHUP.\r\n\r\n",
    "CHINESE KETCHUP--I'VE NEVER\r\n HEARD IT CALLED THAT.\r\n\r\n",
    "THEN WE JUST PUT A LITTLE OF\r\n THE MEAT AND VEG IN THE MIDDLE\r\n\r\n",
    "AND THEN JUST A LITTLE EGG WASH\r\n RIGHT UP AT THE TOP THERE.\r\n\r\n",
    "THEN I'LL, LIKE, ROLL 'EM UP\r\n  IN SOME CORNSTARCH HERE,\r\n\r\n",
    "AND THAT'LL DRY UP\r\n     THE OUTSIDES.\r\n\r\n",
    "IT WILL ALSO\r\n   ADD A LITTLE CRUNCH.\r\n\r\n",
    "ALL RIGHT,\r\nSO NOW DEEP-FRY 'EM?\r\n      THROW 'EM\r\n     IN THE FRYER.\r\n\r\n",
    "NICE\r\n    AND GOLDEN BROWN.\r\nNICE AND TOASTY.\r\n\r\n",
    "GIVE 'EM A SECOND\r\n TO DRAIN.\r\n\r\n",
    "THAT IS BEAUTIFUL.\r\n     LOOK AT THAT.\r\n\r\n",
    "AS SOON AS YOU CUT IT OPEN,\r\n   YOU CAN SEE DUCK.\r\n\r\n",
    "TASTY.\r\nTASTE THE DUCK.\r\n\r\n",
    "DUCK'S NICE. YOU KNOW WHAT\r\n I TASTE? YOU KNOW WHAT I TASTE?\r\n\r\n",
    "I TASTE\r\n     THE FIVE SPICE.\r\nYEAH.\r\n\r\n",
    "I REALLY PICK UP THE FIVE\r\n   SPICE IN THE DUCK.\r\n\r\n",
    "IT'S DELICIOUS.\r\n\r\n",
    "<i> AND IT'S NOT JUST</i>\r\n  <i> THE FRIED STUFF.</i>\r\n\r\n",
    "<i> FOLKS HERE SAY THE ENTIRE MENU</i>\r\n <i> HITS A WHOLE NOTHER LEVEL,</i>\r\n\r\n",
    "<i> EVEN THE DINER BASICS,</i>\r\n\r\n",
    "<i> LIKE MEAT LOAF</i>\r\n  <i> OR THE GRILLED CHEESE.</i>\r\n\r\n",
    "WELCOME TO ITALY. HERE\r\nIS SOME FRESH-BAKED FOCACCIA.\r\n\r\n",
    "<i> AND CHECK OUT THE WINGS.</i>\r\n\r\n",
    "THEY'RE THE BEST WINGS\r\n  I EVER HAD--THE BEST.\r\n\r\n",
    "<i> FRESH WINGS IN A DRY RUB</i>\r\n  <i> WITH CUMIN, GARLIC,</i>\r\n\r\n",
    "<i> PAPRIKA AND MORE.</i>\r\n\r\n",
    "SO THIS MUST BE ONE OF\r\n THE FRENCH DISHES YOU LEARNED.\r\n\r\n",
    "YEAH, THIS\r\n    IS SOUTHERN FRANCE.\r\nYEAH.\r\n\r\n",
    "SO THEY BAKE FIRST\r\n    FOR HOW LONG?\r\n FOR, LIKE,\r\n45, 50 MINUTES.\r\n\r\n",
    "AND NOW WE'RE\r\nGONNA FRY 'EM.\r\n     JUST, LIKE,\r\n    TWO, THREE MINUTES.\r\n\r\n",
    "JUST HEAT 'EM UP,\r\n     CRISP 'EM UP.\r\n THEY'RE GONNA\r\nHEAT UP REALLY FAST.\r\n\r\n",
    "HEAT 'EM UP,\r\nCRISP 'EM UP.\r\n   UH, WE HAVE THE WING\r\n    SAUCE RIGHT HERE.\r\n\r\n",
    "SO THAT IS CHIPOTLE\r\n PEPPERS, BUTTER,\r\n\r\n",
    "A HOT SAUCE MIXTURE--\r\nA CAYENNE HOT SAUCE--\r\n\r\n",
    "A LITTLE BIT\r\nOF DIJON MUSTARD.\r\n    ...AND SRIRACHA.\r\n\r\n",
    "I'M DYIN'\r\nTO TRY THESE.\r\n\r\n",
    "WOW, THAT'S SAVunflORY.\r\n\r\n",
    "I GOTTA TELL YA...\r\n\r\n",
    "THAT'S A PRIMO WING,\r\n     BRO.\r\n\r\n",
    "I'D EAT THOSE\r\n     EVERY DAY.\r\n\r\n",
    "<i> ...OR THE EMPANADAS</i>\r\n  <i> OR THE SPRING ROLLS</i>\r\n\r\n",
    "<i> OR THE POT STICKERS</i>\r\n <i> OR ANYTHING ON PETER'S MENU.</i>\r\n\r\n",
    "HAVE YOU TRIED THIS?\r\n\r\n",
    "<i> JUST ASK THE GROWING</i>\r\n   <i> CROWD OF FANS.</i>\r\n\r\n",
    "WELL, I TRIED A LOT OF THINGS\r\n I NORMALLY WOULDN'T EAT,\r\n\r\n",
    "AND THEY WERE ALL GOOD.\r\n\r\n",
    "IT'S NOT JUST AMERICAN FOOD.\r\n   IT'S A NICE MIX.\r\n\r\n",
    "GOOD RESTAURANT FOOD IN A DINER.\r\n\r\n",
    "<i> AFTER ALL, GOOD FOOD</i>\r\n  <i> AT A GOOD PRICE</i>\r\n\r\n",
    "<i> IS WHAT THE CLASSIC DINER</i>\r\n   <i> IS ALL ABOUT.</i>\r\n\r\n",
    "<i> NOW THROW IN GREAT FOOD</i>\r\n  <i> AND A VELVET ELVIS--</i>\r\n\r\n",
    "<i> HOW CAN YOU MISS?</i>\r\n\r\n",
    "I LOVE THE PEOPLE.\r\nI LOVE MAKING PEOPLE HAPPY\r\n\r\n",
    "AND JUST\r\nTHROWING A PARTY.\r\n\r\n",
    "<i> UP NEXT...</i>\r\n\r\n",
    "TWO SPECIALS.\r\n\r\n",
    "<i> THE CLASSIC DRIVE-IN</i>\r\n\r\n",
    "<i> WHERE CALIFORNIANS</i>\r\n <i> ARE JAMMIN' THE JOINT...</i>\r\n\r\n",
    "THIS LINE JUST KEEPS\r\n    LONGER AND LONGER.\r\n  ALWAYS CROWDED.\r\n\r\n",
    "<i> FOR FAST FOOD</i>\r\n  <i> MIDDLE EASTERN-STYLE.</i>\r\n\r\n",
    "I NEVER GET TIRED\r\n  OF THE FALAFELS.\r\n\r\n",
    "ON \"DINERS, DRIVE-INS\r\n   AND DIVES,\"\r\n\r\n",
    "I'VE TASTED MY WAY\r\n  ACROSS THE COUNTRY,\r\n\r\n",
    "AND ONE OF THE THINGS\r\n  I'VE COME TO LEARN\r\n\r\n",
    "IS TO EXPECT THE UNEXPECTED.\r\n\r\n",
    "NOW I'D EXPECT TO FIND GREAT\r\n FOOD IN SAN JOSE, CALIFORNIA,\r\n\r\n",
    "BUT WHAT'S UNEXPECTED\r\n\r\n",
    "IS THAT IT WOULD BE A FRIED\r\n FALAFEL FROM A DRIVE-IN.\r\n\r\n",
    "TWO SPECIALS.\r\n\r\n",
    "DO YOU KNOW WHAT'S\r\n    IN A FALAFEL?\r\nNOT REALLY.\r\n\r\n",
    "NOT REALLY.\r\n     DO YOU CARE?\r\nNO.\r\n\r\n",
    "I JUST KNOW\r\nIT TASTES GOOD.\r\n\r\n",
    "THEY'RE BIG AND GREEN AND YUMMY.\r\n\r\n",
    "<i> THEY'RE MADE OF DEEP-FRIED</i>\r\n   <i> CHICK PEAS.</i>\r\n\r\n",
    "THREE LARGE FALAFELS\r\n   AND ONE SMALL FALAFEL.\r\n\r\n",
    "I NEVER GET TIRED\r\n  OF THE FALAFELS.\r\n\r\n",
    "<i> THEY'VE BEEN FAST FOOD</i>\r\n <i> IN THE MIDDLE EAST FOREVER...</i>\r\n\r\n",
    "WE ALWAYS\r\n    HAD THAT SAYING--\r\n\r\n",
    "\"FEELING AWFUL?\r\n    HAVE A FALAFEL.\"\r\n\r\n",
    "<i> AND A LOCAL FAVORITE</i>\r\n <i> AT THIS JOINT FOR 40 YEARS.</i>\r\n\r\n",
    "THERE, SIR.\r\nTHANK YOU.\r\n\r\n",
    "THIS LINE JUST KEEPS\r\n    LONGER AND LONGER.\r\n  IT'S ALWAYS CROWDED.\r\n\r\n",
    "IT IS ALWAYS\r\n      CROWDED?\r\n   ALWAYS.\r\n\r\n",
    "YOU'VE HAD FALAFELS\r\n  BEFORE...\r\n       YEAH.\r\n\r\n",
    "AT A DRIVE-IN?\r\n        NO.\r\n\r\n",
    "IT'S AN ODD COMBINATION.\r\n\r\n",
    "CALIFORNIA FUSION.\r\n\r\n",
    "THE FALAFEL BALLS\r\n ARE GOOD.\r\n\r\n",
    "- FALAFEL SANDWICHES.\r\n-      I GET     THE FALAFEL SALAD.\r\n\r\n",
    "IT'S MY FATHER'S RECIPE.\r\n   IT WILL NEVER CHANGE.\r\n\r\n",
    "IT JUST--IT'S GOD.\r\nTHE WAY IT IS,\r\nAND THAT'S IT.\r\n\r\n",
    "YEAH, NO ONE CAN TOUCH IT.\r\n    IT'S AMAZING.\r\n\r\n",
    "THIS IS MY DAD.\r\n   WOW, IS THAT A DUDE\r\n   OF CHARACTER OR WHAT?\r\n\r\n",
    "HE HAD A PASSION FOR FOOD.\r\n  HE LOVED IT--EVERYTHING.\r\n\r\n",
    "HE WAS ALWAYS\r\n   IN THE KITCHEN COOKING.\r\n\r\n",
    "<i> ANTON NIJMEH BOUGHT</i>\r\n  <i> THIS PLACE BACK IN '66</i>\r\n\r\n",
    "<i> AFTER MOVING HIS FAMILY HERE</i>\r\n  <i> FROM THE MIDDLE EAST.</i>\r\n\r\n",
    "TWO SPECIALS.\r\n\r\n",
    "MY DAD SEES THIS BURGER JOINT,\r\n   AND HE GOES,\r\n\r\n",
    "\"OH, EVERYBODY\r\nHAS BURGERS.\"\r\n\r\n",
    "HE'S ALL--THIS IS--HE'S GONNA\r\n  GIVE HIS FALAFEL--\r\n    OOH, BUT WHO HAS\r\n    A FALAFEL DRIVE-IN?\r\n\r\n",
    "HE WAS GIVING FALAFELS\r\n FOR FREE FOR A LONG TIME.\r\nAND 41 YEARS AGO,\r\n\r\n",
    "NO ONE KNEW, REALLY,\r\nWHAT A FALAFEL WAS.\r\n\r\n",
    "HE'D MAKE 'EM TRY IT.\r\n IT WAS LIKE, YEAH,\r\nCOME FOR THE BURGER,\r\n\r\n",
    "BUT HERE,\r\nTRY A FALAFEL.\r\n     ...BUT TRY IT.\r\n\r\n",
    "AND THEN IT MADE\r\nTHE TRANSITION.\r\n    AND THEY DID.\r\n   THEY'D TASTE IT AND GO,\r\n\r\n",
    "\"OH, WOW,\r\n   THAT IS KIND OF GOOD.\"\r\n\r\n",
    "<i> FOUR DECADES LATER,</i>\r\n\r\n",
    "<i> THE FAMILY'S</i>\r\n  <i> KEEPING IT THAT WAY.</i>\r\n\r\n",
    "I MEAN, THE PLACE IS FABULOUS.\r\n\r\n",
    "<i> DAUGHTER JOANNE'S</i>\r\n   <i> AT THE WINDOW.</i>\r\n\r\n",
    "NEXT.\r\n\r\n",
    "THEY LOVE YOU HERE.\r\n\r\n",
    "<i> AND SON-IN-LAW NASSIF</i>\r\n  <i> IS RUNNING THE LINE.</i>\r\n\r\n",
    "AS FAST AS YOU CAN GET 'EM\r\n FROM HIM AND WRAP 'EM...\r\n       WHOO.\r\n\r\n",
    "IS AS FAST\r\nAS THEY GO?\r\n\r\n",
    "NUMBER 25, 26, 27, 28.\r\n\r\n",
    "YOU'RE THE FALAFELNATOR.\r\n  LOOK AT HIM. HE'S IN IT.\r\n  ALL RIGHT, GUY.\r\n\r\n",
    "DRY BEANS--WE SOAK\r\n   THEM OVERNIGHT.\r\n\r\n",
    "SO DRY CHICK PEAS.\r\nDRY CHICK PEAS.\r\n\r\n",
    "WE DRAIN 'EM\r\nAND WASH 'EM.\r\n\r\n",
    "I'M GONNA GET YA\r\nA BIGGER COLANDER.\r\n\r\n",
    "IT LOOKS LIKE\r\n     SNUFFLEUPAGUS.\r\n\r\n",
    "WELL, SO MANY\r\n YEARS OF--\r\n      ARRRRRR.\r\n\r\n",
    "WOW, YOU COULD GET RID\r\n   OF A BODY IN THIS.\r\n\r\n",
    "THAT'S THE BASE FOR\r\nTHE AWESOME FALAFEL MIX.\r\n     IS THAT WHAT\r\n     IT'S CALLED?\r\n\r\n",
    "YEAH.\r\n   AWESOME FALAFEL MIX?\r\n\r\n",
    "<i> YOU HAVE TO BE A MEMBER</i>\r\n   <i> OF THE FAMILY</i>\r\n\r\n",
    "<i> TO KNOW WHAT COMES NEXT.</i>\r\n\r\n",
    "IT'S MOSTLY HERBS.\r\n   OH, SO YOU'RE NOT GONNA\r\n   TELL ME WHAT'S IN THIS,\r\n\r\n",
    "AND YOU'RE NOT GONNA\r\n  TELL ME THE MIX OF SPICES?\r\nEH, JUST SPICES.\r\n\r\n",
    "WE GOT CUMIN,\r\n     SALT, SUGAR.\r\n\r\n",
    "...CARAWAY SEEDS, A LITTLE\r\nOF THIS, A LITTLE, YOU KNOW?\r\n\r\n",
    "AND WHEN YOU MIX IT\r\nWITH THIS, IT'S HEAVENLY.\r\n\r\n",
    "IT SMELLS GREAT.\r\nTHAT'S PRETTY MUCH--\r\n\r\n",
    "THAT'S FALAFELNATED?\r\nTHAT'S FALAFEL.\r\n\r\n",
    "WHAT IS THIS THING?\r\nTHAT'S A FALAFEL MAKER.\r\n\r\n",
    "IT MAKES\r\nFALAFEL BALLS.\r\n     CAN I DO ONE?\r\n\r\n",
    "YEAH.\r\n   AND YOU SMEAR IT IN?\r\n\r\n",
    "YEAH, YOU WANT TO PRESS IT\r\nA LITTLE BIT HARD INSIDE.\r\n\r\n",
    "ALL RIGHT,\r\nGUY IS COOKIN'.\r\n  YEAH, I JUST WANT TO BE\r\n  CALLED THE FALAFELNATOR.\r\n\r\n",
    "CAN WE FRY THOSE?\r\nDO WE HAVE A CEREMONY?\r\n\r\n",
    "NO, IT'S REAL SLOW.\r\nOH, REAL SLOW?\r\n\r\n",
    "YEAH, OTHERWISE IT WOULD\r\n   JUST BREAK APART.\r\n\r\n",
    "KEEP 'EM LIKE THIS\r\n    FOR HALF A MINUTE\r\n\r\n",
    "TILL THEY JUST\r\n    CRISP A LITTLE BIT.\r\n\r\n",
    "YEAH, AND THEN\r\nYOU LET THEM SIT.\r\n\r\n",
    "YOU LET THEM JUST SOAK\r\nIN THE OIL TILL THEY--\r\n\r\n",
    "YOU LET THEM COOK FOR,\r\nLIKE, 3 1/2, 4 MINUTES.\r\n\r\n",
    "LOOK AT THE COLOR\r\n OF THOSE?\r\n       HUH?\r\n\r\n",
    "<i> YOU CAN EAT 'EM STRAIGHT UP...</i>\r\n\r\n",
    "THAT'S THE BOMB FALAFEL.\r\n\r\n",
    "<i> OR ON A SALAD OR A PITA</i>\r\n<i>SANDWICH WITH HOMEMADE TAHINI--</i>\r\n\r\n",
    "<i> THAT'S A SESAME SAUCE--</i>\r\n <i> AND A KILLER HOT SAUCE.</i>\r\n\r\n",
    "THE MIXTURE OF THOSE\r\n   FLAVORS TOGETHER--\r\n\r\n",
    "THIS IS FANTASTIC\r\n     FALAFEL.\r\n\r\n",
    "THIS ONE'S JUST GOT\r\nTHE RIGHT AMOUNT OF SAUCE.\r\n\r\n",
    "WONDERFUL.\r\n\r\n",
    "WE USE SOYBEAN OIL,\r\n  YOU KNOW,\r\n\r\n",
    "AND IT FRIES SO HOT\r\nTHAT IT DOESN'T HAVE ANY...\r\n\r\n",
    "'CAUSE IT'S NOT OILY.\r\nNO.\r\n\r\n",
    "IT'S FALAFELICIOUS.\r\n\r\n",
    "I'M CHANGING YOUR NAME.\r\n   YOU'RE FALAFEL KING.\r\n\r\n",
    "LET'S MAKE SEVEN MORE.\r\n\r\n",
    "IT'S AMAZING THE PEOPLE\r\n    THAT COME HERE.\r\n\r\n",
    "YOU GET TRUCKERS.\r\n    YOU GET SUITS.\r\n\r\n",
    "YOU GET KIDS.\r\n    KIDS LIKE IT NOW.\r\n\r\n",
    "IT'S YUMMY.\r\n\r\n",
    "IT'S ONE OF, YOU KNOW,\r\n THE GREAT PLACES AROUND--\r\n\r\n",
    "THE LITTLE FINDS--THAT YOU\r\n WON'T GET ANYWHERE ELSE.\r\n\r\n",
    "IT'S NOT A CHAIN,\r\n  AND IT'S REAL FOOD.\r\n\r\n",
    "<i> AND BEYOND THE FALAFEL...</i>\r\n\r\n",
    "I'LL HAVE\r\n     A LARGE GYRO.\r\n\r\n",
    "<i> THEY'VE GOT A WHOLE MENU</i>\r\n\r\n",
    "<i> OF MIDDLE EASTERN</i>\r\n  <i> FAST FOOD FAVORITES,</i>\r\n\r\n",
    "<i> LIKE THE KIFTA KABAB,</i>\r\n\r\n",
    "THE MIDDLE EASTERN VERSION\r\n OF AN ALL-AMERICAN CLASSIC.\r\n\r\n",
    "THAT'S\r\n    THEIR HAMBURGER.\r\n\r\n",
    "GROUND BEEF, ONIONS.\r\n\r\n",
    "ABOUT 600,000 POUNDS\r\n  OF PARSLEY.\r\n    NO, JUST A BUNCH.\r\n\r\n",
    "A MAN\r\nAND HIS MACHINE.\r\n\r\n",
    "RIGHT IN?\r\n     YES, PLEASE.\r\n\r\n",
    "NOW--\r\n    SALT, CORIANDER,\r\n   A LITTLE BIT OF GARLIC,\r\n\r\n",
    "A LITTLE BIT\r\n     OF CUMIN...\r\nMMM.\r\n\r\n",
    "PAPRIKA,\r\n    A PINCH OF NUTMEG.\r\n THEN PUT IT\r\nON THE STICK?\r\n\r\n",
    "NO, YOU WANT IT ON A SKEWER.\r\n  THAT'S A SHISH KABAB.\r\n\r\n",
    "OH, SO YOU CAN CALL IT A KABAB\r\nEVEN THOUGH IT'S NOT ON A STICK?\r\n      THAT'S\r\n     A KIFTA KABAB?\r\n\r\n",
    "KIFTA MEANS SOMETHING YOU PUT IN\r\n YOUR HAND AND YOU MAKE A BALL.\r\n\r\n",
    "YOU KIFTA IT?\r\n      EXACTLY.\r\n\r\n",
    "NOW WE'RE GONNA\r\nGRILL SOME KABABS.\r\n\r\n",
    "CUT IT IN HALF.\r\n   ...STUFF IT IN A PITA.\r\n\r\n",
    "WOW.\r\n   TAHINI SAUCE WITH MIXED\r\n    VEGETABLE TO IT.\r\n\r\n",
    "AND THE MAJORITY OF THE PEOPLE\r\n   LOVE HOT SAUCE.\r\n\r\n",
    "AND BON APPéTIT.\r\n     ENJOY.\r\n\r\n",
    "THAT'S LIKE\r\nA MEDITERRANEAN MEATBALL.\r\n\r\n",
    "LOOK AT THAT.\r\n\r\n",
    "THE SEASONINGS REALLY\r\n WORK WELL WITH THE MEAT.\r\n\r\n",
    "GO AHEAD AND JUST\r\nKEEP WORKING. I'M FINE.\r\n\r\n",
    "<i> GETTIN' THIRSTY, THOUGH.</i>\r\n\r\n",
    "<i> SO CHECK OUT THIS</i>\r\n   <i> HOUSE SPECIAL.</i>\r\n\r\n",
    "HOW ARE\r\n    THE BANANA SHAKES?\r\nOH, THEY'RE THE BEST.\r\n\r\n",
    "WHAT IF YOU DON'T\r\n     LIKE BANANAS?\r\nWELL, THEN I GUESS YOU DON'T\r\n GET THE BANANA SHAKE.\r\n\r\n",
    "BA-DUM-BUM.\r\n   BUT SERIOUSLY, JOHNNY.\r\n\r\n",
    "SO WHO MADE UP  THE BANANA SHAKE?\r\n      MY FATHER DID.\r\n\r\n",
    "HE LOVED FRESH FRUIT,\r\n\r\n",
    "AND THAT WAS THE ONLY ONE\r\n  YOU CAN GET YEAR-ROUND.\r\n\r\n",
    "SLICE IT.\r\nOH, AND THAT'S HOW YOU SLICE\r\nIT--ON THE EDGE OF THE CUP?\r\n\r\n",
    "NONFAT MILK.\r\nLET ME SEE THAT\r\n ARM STRENGTH.\r\n\r\n",
    "I LOOK SMALL,\r\n    BUT I GOT MUSCLES.\r\nREALLY? YOU CAN\r\nTAKE 'EM DOWN?\r\n\r\n",
    "YEAH, I CAN. I GOT\r\n   THREE BROTHERS, TOO.\r\n\r\n",
    "MMM, THAT'S LITERALLY BANANAS.\r\n\r\n",
    "<i> IT GOES SO WELL</i>\r\n <i> WITH FALAFEL AND HOT SAUCE...</i>\r\n\r\n",
    "IT KIND OF PUTS OUT THE FIRE\r\nIN THE HOT SAUCE, YOU KNOW?\r\n\r\n",
    "<i> THAT IT'S THE HOT COMBO</i>\r\n   <i> ON THE MENU.</i>\r\n\r\n",
    "THE FALAFEL WITH BANANA\r\n SHAKE SPECIAL.\r\n\r\n",
    "TWO FALAFEL\r\n  WITH BANANA SHAKES?\r\n\r\n",
    "PEOPLE SAY THEY MOVED AWAY,\r\n   AND THEY COME BACK,\r\n\r\n",
    "\"GOD, I JUST HAD TO COME OVER\r\n HERE AND COME TO THIS PLACE.\r\n\r\n",
    "\"I JUST LEFT THE AIRPORT,\r\n  AND I'M BACK FOR A WEEK,\r\n\r\n",
    "AND I'M GONNA BE HERE EVERY DAY\r\n UNTIL I LEAVE TO GET THE--\"\r\n\r\n",
    "YOU KNOW?\r\n ...TO GET\r\nMY FALAFEL FIX.\r\n\r\n",
    "THAT'S WHAT\r\n   THEY CALL IT--THE FIX.\r\n\r\n",
    "<i> ...EVEN IF THEY STILL</i>\r\n <i> DON'T KNOW WHAT IT IS.</i>\r\n\r\n",
    "YOU KNOW HOW\r\n  THE FALAFELS ARE MADE?\r\nYUMMILY.\r\n\r\n",
    "YUMMILY?\r\n  THEY'RE MADE YUMMILY?\r\nYES.\r\n\r\n",
    "OHH, I GOTTA\r\n   USE THAT.\r\n\r\n",
    "WELL, THESE ARE ACTUALLY\r\n   MADE WITH A LOT\r\n\r\n",
    "OF YUMMYLICIOUS-ISH-NESS.\r\nYUMMYLICIOUS.\r\n\r\n",
    "YUMMY-LISH-NESS.\r\nLISH-IS-NESS.\r\n\r\n",
    "YUMMY-LICIOUSNESS.\r\n\r\n",
    "<i> NEXT UP, I'M HEADIN'</i>\r\n   <i> DOWN THE COAST</i>\r\n\r\n",
    "<i> TO A SMALL-TOWN CAFé...</i>\r\n\r\n",
    "IT'S THE BEST FOOD IN TOWN.\r\n\r\n",
    "<i> WHERE FRENCH-FRYING</i>\r\n  <i> DOESN'T MEAN POTATOES.</i>\r\n\r\n",
    "THAT'S FRIED CRUNCH-A-LICIOUS\r\n   RIGHT THERE.\r\n\r\n",
    "SO I'M IN RAMONA, CALIFORNIA,\r\n\r\n",
    "WHICH IS ABOUT AN HOUR\r\n NORTHEAST OF SAN DIEGO,\r\n\r\n",
    "RIGHT AT THE GATEWAY\r\n   OF THE DESSERT.\r\n\r\n",
    "NOW IN THE MIDDLE OF TOWN\r\n  IS THIS LITTLE JOINT\r\n\r\n",
    "OWNED BY THE DAUGHTER\r\n OF A LOCAL EGG FARMER...\r\n\r\n",
    "FRIES READY?\r\n\r\n",
    "<i> THE KIND OF PLACE YOU'D EXPECT</i>\r\n  <i> BASIC CAFé COOKING...</i>\r\n\r\n",
    "HERE YOU GO.\r\n      THANK YOU.\r\n\r\n",
    "<i> NOT A HOMEMADE CHICKEN CORDON</i>\r\n <i> BLEU WITH FRESH HOLLANDAISE.</i>\r\n\r\n",
    "IT'S SPICY AND TENDER.\r\n\r\n",
    "REALLY GOOD.\r\n\r\n",
    "<i> AND GET THIS--IT'S DEEP-FRIED.</i>\r\n\r\n",
    "I DON'T THINK I'VE EVER SEEN\r\n CHICKEN CORDON BLEU SUBMERGED.\r\n\r\n",
    "WHY DEEP-FRY IT?\r\n   IT JUST TASTES BETTER.\r\n\r\n",
    "IT HAS A CRISPY TEXTURE\r\n   TO THE EXTERIOR,\r\n\r\n",
    "AND IT TASTES\r\n     REALLY YUMMY.\r\n\r\n",
    "<i> SO DOES THE FRIED CHICKEN</i>\r\n <i> AND THE CHICKEN-FRIED STEAK</i>\r\n\r\n",
    "<i> AND FISH AND CHIPS.</i>\r\n\r\n",
    "<i> EVEN THE KID-FRIENDLY CHICKEN</i>\r\n  <i> STRIPS ARE HOMEMADE,</i>\r\n\r\n",
    "<i> JUST LIKE ALMOST</i>\r\n  <i> EVERYTHING HERE.</i>\r\n\r\n",
    "THIS IS GOOD.\r\n\r\n",
    "IT'S THE BEST FOOD IN TOWN.\r\n\r\n",
    "ANYBODY KNOW WHERE\r\n   RAMONA CAFé IS?\r\n\r\n",
    "<i> ...A SMALL-TOWN LANDMARK,</i>\r\n\r\n",
    "<i> A 26-YEAR-OLD LOCAL LEGEND...</i>\r\n\r\n",
    "IT'S VERY HOMEY.\r\n\r\n",
    "IS THIS MY TWIN, HUH?\r\n\r\n",
    "GREAT SERVICE--REALLY FRIENDLY.\r\n\r\n",
    "<i> RUN BY A LOCAL LEGEND...</i>\r\n\r\n",
    "ALL RIGHT,\r\nHERE YOU GO.\r\n\r\n",
    "<i> SONJA VANDERVEEN.</i>\r\n\r\n",
    "CINNAMON ROLL\r\n FOR YOU.\r\n\r\n",
    "SONJA IS SUCH A PIE.\r\n  SHE'S REALLY SWEET.\r\n\r\n",
    "WHEN DID THEY\r\nPUT STOPLIGHTS IN?\r\n      OH, MY GOD.\r\n\r\n",
    "THE FIRST SIGNAL\r\n    WENT IN IN '79\r\n\r\n",
    "WHEN I GRADUATED\r\n    FROM HIGH SCHOOL.\r\n\r\n",
    "<i> SONJA LEFT FOR A WHILE</i>\r\n  <i> AFTER SHE GRADUATED,</i>\r\n\r\n",
    "<i> THEN CAME BACK HOME.</i>\r\n\r\n",
    "<i> 20 YEARS AGO,</i>\r\n  <i> SHE BOUGHT THIS PLACE</i>\r\n\r\n",
    "<i> WITH SOME HELP</i>\r\n  <i> FROM HER PARENTS,</i>\r\n\r\n",
    "<i> INCLUDING SOME RECIPES</i>\r\n <i> FROM HER SWISS-BORN MOM.</i>\r\n\r\n",
    "NOW I GET IT. I DIDN'T KNOW\r\n THERE WAS SWISS INFLUENCE.\r\n     OH, YEAH.\r\n\r\n",
    "DID YOU MAKE CHICKEN CORDON\r\n  BLEU WHEN YOU WERE A KID?\r\n\r\n",
    "DID YOUR MOM\r\n    COOK IT FOR YOU?\r\nYES.\r\n\r\n",
    "SO THIS IS JUST KIND\r\n   OF YOUR ADAPTATION.\r\nTRADITIONAL.\r\n\r\n",
    "SO TAKE ME\r\n      THROUGH IT.\r\n OKAY, YOU TAKE\r\nA CHICKEN BREAST,\r\n\r\n",
    "AND WE CUT IT\r\n IN HALF.\r\n\r\n",
    "THEN WE PLACE THE PLASTIC\r\n WRAP OVER THE CHICKEN,\r\n\r\n",
    "BECAUSE WE'RE GONNA\r\n POUND IT OUT.\r\n    YOU DON'T WANT IT\r\n     TO K-K-K-K-K?\r\n\r\n",
    "RIGHT. 1/4-INCH THICK.\r\n\r\n",
    "ALL RIGHT. TAKE\r\nTHE SARAN WRAP OFF,\r\n\r\n",
    "AND PLACE THE HAM\r\n IN THE MIDDLE\r\n\r\n",
    "AND GRUYèRE\r\nSWISS CHEESE.\r\n   YOU REALLY HAVE TO USE\r\n   THE GRUYèRE CHEESE?\r\n\r\n",
    "YES, YOU DO. IT REALLY\r\nADDS THAT EXTRA FLAVOR.\r\n    THAT'S THE TANG.\r\n     THAT'S RIGHT.\r\n\r\n",
    "AND THEN WHAT\r\n    DO YOU DO TO IT?\r\nROLL IT UP.\r\n\r\n",
    "AND WE SECURE IT\r\nWITH TOOTHPICKS.\r\n   AND I'D EAT THAT\r\n  IF I LIKED CHICKEN CEVICHE.\r\n\r\n",
    "NOW WHEN YOU FIRST\r\n   PUT THIS ON THE MENU,\r\n\r\n",
    "DID PEOPLE\r\n    JUST GO BANANAS?\r\nTHEY DID. THEY LOVE IT.\r\n  OH, MY GOSH.\r\n\r\n",
    "BANANAS IS GOOD.\r\n  BANANAS IS GOOD\r\nWITH CHICKEN CORDON BLEU--\r\n\r\n",
    "FRIED BANANAS.\r\n\r\n",
    "MOST PEOPLE JUST BAKE IT AND PUT\r\n THE STUFF ON IT, AND THAT'S IT,\r\n\r\n",
    "BUT WE'RE\r\n     GONNA FRY IT.\r\nRIGHT, WE'RE GONNA\r\n DEEP-FRY IT.\r\n\r\n",
    "OKAY, WE'RE GONNA\r\n     DIP IT IN EGG.\r\n STRAIGHT-UP EGG,\r\nOR IS IT EGG WASH?\r\n\r\n",
    "IT'S STRAIGHT-UP EGG.\r\nSTRAIGHT-UP EGG.\r\n\r\n",
    "SO IT'S\r\nREALLY GONNA--\r\n   THEN WE'RE GONNA DO IT\r\n   AGAIN ONE MORE TIME.\r\n\r\n",
    "OH, WE'RE GONNA\r\nDO THIS BA--OH.\r\n\r\n",
    "SO YOU REALLY ARE THE COLOSSAL\r\n  KING KONG OF CRUST?\r\n      DEFINITELY.\r\n\r\n",
    "DROP IT.\r\nSAY \"HAMMER IT.\"\r\n      HAMMER IT.\r\n\r\n",
    "I'M THE COLOSSAL\r\nKING KONG OF CRUST.\r\n     COLOSSAL\r\n    KING KONG OF CRUST.\r\n\r\n",
    "OH, WE SET A TIMER?\r\n   YOU LOVE YOUR TIMER.\r\n\r\n",
    "SEE, YOU'RE A BAKER.\r\n\r\n",
    "IT LOOKS GOOD.\r\n\r\n",
    "MMM.\r\n\r\n",
    "THAT CHEESE\r\n    REALLY STANDS OUT.\r\nDOESN'T IT?\r\n\r\n",
    "IT REALLY STANDS OUT IN THAT.\r\n DEFINITELY IS THE CRUNCHIEST.\r\n\r\n",
    "I MEAN, THAT HAS\r\n    A TEXTURE ON THAT.\r\n\r\n",
    "<i> THE KEY TO THE CRUNCH</i>\r\n <i> IS SONJA'S HOMEMADE BREADING,</i>\r\n\r\n",
    "<i> MADE FROM HOMEMADE BISCUITS</i>\r\n\r\n",
    "<i> THAT HAVE BEEN SITTING</i>\r\n  <i> AROUND A WHILE.</i>\r\n\r\n",
    "AND WE DRY 'EM OUT\r\n A LITTLE BIT.\r\n    THIS IS DRIED OUT\r\n     A LITTLE BIT?\r\n\r\n",
    "A LOT. THEY'RE STALE.\r\n     SO A LITTLE\r\n     BIT OF FLOUR.\r\n\r\n",
    "SO LIKE A 50-50\r\n     MIXTURE?\r\nYEAH, A 50-50\r\n MIXTURE.\r\n\r\n",
    "PEPPER, A 1/2 TEASPOON\r\n  OF CAYENNE,\r\n\r\n",
    "A TABLESPOON\r\nOF POULTRY SEASONING.\r\n     HOW MUCH SALT?\r\n\r\n",
    "A 1/2 TEASPOON.\r\n AND CAJUN.\r\n\r\n",
    "NOT TOO SPICY. OKAY.\r\n\r\n",
    "<i> SONJA USES THAT SAME BREADING</i>\r\n\r\n",
    "<i> ON HER BUTTERMILK</i>\r\n   <i> FRIED CHICKEN.</i>\r\n\r\n",
    "THAT'S FRIED CRUNCH-A-LICIOUS\r\n   RIGHT THERE.\r\nOH, GOOD.\r\n\r\n",
    "<i> SHE ALSO USES IT ON HER</i>\r\n  <i> CHICKEN-FRIED STEAK...</i>\r\n\r\n",
    "VERY GOOD.\r\n\r\n",
    "<i> WHICH IS REALLY MOIST.</i>\r\n\r\n",
    "JUICY.\r\n\r\n",
    "<i> AND HERE'S THE TWIST--</i>\r\n <i> SONJA'S CHICKEN-FRIED STEAK--</i>\r\n\r\n",
    "<i> INSTEAD OF A SOLID</i>\r\n  <i> PIECE OF BEEF--</i>\r\n\r\n",
    "<i> IS A 50-50 MIXTURE</i>\r\n <i> OF GROUND BEEF AND VEAL.</i>\r\n\r\n",
    "I THINK THE VEAL AND THE BEEF\r\nIDEA OF CHICKEN-FRIED STEAK--\r\n\r\n",
    "NICE BIG AND VERY\r\n  FLAVORFUL, FLUFFY.\r\n\r\n",
    "IT'S GOT A LITTLE BIT\r\n OF A PEPPERY TASTE TO IT.\r\n\r\n",
    "OKAY.\r\n\r\n",
    "THAT IS REALLY GOOD.\r\nTHE BREADING'S NOT TOO THICK,\r\n\r\n",
    "AND THE MEAT IS NICE\r\n AND MOIST INSIDE.\r\n       YES.\r\n\r\n",
    "THAT'S WHAT I LIKE\r\n     ABOUT IT.\r\n AND THERE'S\r\nA LOT OF FLAVOR.\r\n\r\n",
    "YOU CAN ACTUALLY\r\n TASTE MEAT.\r\n\r\n",
    "YOU'RE NOT JUST TASTING\r\nFRIED BATTER, FRIED THING.\r\n\r\n",
    "<i> THE LOCALS SAY IT'S THE SAME</i>\r\n  <i> WITH EVERYTHING HERE--</i>\r\n\r\n",
    "<i> REAL HOME COOKIN'</i>\r\n<i>THAT TASTES LIKE SOMEONE CARES.</i>\r\n\r\n",
    "I MEAN, IT'S LIKE ALL\r\n THE FLAVORS COME TOGETHER,\r\n\r\n",
    "AND IT TASTES REALLY GOOD.\r\n\r\n",
    "<i> AND REAL HOME BAKING, TOO.</i>\r\n\r\n",
    "<i> WHEN WE COME BACK, I'M MAKING</i>\r\n <i> A LITTLE SOMETHING SWEET</i>\r\n\r\n",
    "<i> TO TOP OFF MY MEAL.</i>\r\n\r\n",
    "<i> AT THE RAMONA CAFé,</i>\r\n\r\n",
    "<i> THE LUNCH AND DINNER CROWD</i>\r\n <i> IS PACKIN' THE JOINT...</i>\r\n\r\n",
    "YOU'RE WELCOME. DO YOU GUYS\r\n NEED ANYTHING ELSE RIGHT NOW?\r\n\r\n",
    "<i> FOR BIG FAVORITES</i>\r\n <i> LIKE CHICKEN CORDON BLEU</i>\r\n\r\n",
    "<i> AND CHICKEN-FRIED STEAK.</i>\r\n\r\n",
    "<i> BUT THIS PLACE IS JUST</i>\r\n <i> AS BIG FOR BREAKFAST...</i>\r\n\r\n",
    "TOMATOES, BACON, GARLIC,\r\n  GREEN BELL PEPPERS.\r\n\r\n",
    "<i> WITH SOMETHING</i>\r\n <i> CALLED THE KITCHEN SINK.</i>\r\n\r\n",
    "CHEDDAR CHEESE.\r\nIS THIS GONNA STOP\r\n AT ANY POINT?\r\n\r\n",
    "JACK CHEESE.\r\n     SOME POINT.\r\n\r\n",
    "<i> THE HAWAIIAN SHORT STACK</i>\r\n  <i> WITH PINEAPPLE,</i>\r\n\r\n",
    "<i> COCONUT AND WHIPPED CREAM</i>\r\n\r\n",
    "<i> AND STRAWBERRY-CREAM-CHEESE-</i>\r\n  <i> STUFFED FRENCH TOAST.</i>\r\n\r\n",
    "ONE OF THE BEST RESTAURANTS\r\n IN THE AREA, YOU THINK?\r\n DEFINITELY.\r\n\r\n",
    "OH, THE BEST.\r\n\r\n",
    "THAT'S LIKE A FOOTBALL.\r\n\r\n",
    "<i> FOR A OT OF FOLKS,</i>\r\n  <i> THE BEST OF THE BEST</i>\r\n\r\n",
    "<i> ARE THE MASSIVE CINNAMON ROLLS</i>\r\n  <i> MADE FRESH EVERY DAY.</i>\r\n\r\n",
    "I SEE THAT YOU'VE OPENED IT AND\r\nDISPLAYED IT FOR ME SO NICELY.\r\n\r\n",
    "BUT I HAVEN'T REALLY FELT\r\nTHE INVITATION TO EAT IT YET.\r\n     OF COURSE NOT.\r\n\r\n",
    "THAT'S FOR ME\r\n     TO TAKE HOME.\r\n\r\n",
    "WHO TAUGHT YOU\r\n    HOW TO MAKE 'EM?\r\nMY MOM.\r\n\r\n",
    "YOUR MOM?\r\n YES. YOU PUT\r\n2 CUPS OF MILK IN,\r\n\r\n",
    "AND THEN YOU THROW IN\r\n4 OUNCES OF MARGARINE.\r\n\r\n",
    "SLOWLY POUR IT\r\n IN THERE.\r\n\r\n",
    "<i> IT'S ALL MIXED UP WITH SALT,</i>\r\n <i> SUGAR, YEAST AND FLOUR.</i>\r\n\r\n",
    "SO THAT'S GONNA WACKA-\r\n WACKA-WACKA FOR FIVE MINUTES?\r\n\r\n",
    "AND THEN YOU PUT IT\r\nIN A BOWL AND LET IT RISE.\r\n\r\n",
    "THEN WE THROW THE BIG\r\n   GOB OF GOO--DOUGH--\r\nTHE BIG GOB OF GOO?\r\n\r\n",
    "THAT'S WHAT I CALL IT.\r\n IS THAT\r\nA BAKING TERM?\r\n\r\n",
    "IT GOT HAPPY HERE.\r\n  OKAY.\r\n     IT GOT HAPPY?\r\n\r\n",
    "YES.\r\n     THE BIG GOB\r\n    OF GOO GOT HAPPY?\r\n\r\n",
    "YOU SHOULD THINK ABOUT PUTTING\r\n OUT, LIKE, A BIG GOB OF GOO\r\n\r\n",
    "WORKOUT VIDEO.\r\nTHERE YOU GO.\r\n\r\n",
    "OKAY, WE GOT\r\nTHE MARGARINE...\r\n       WOW.\r\n\r\n",
    "AND WE'RE GONNA SPREAD THAT\r\n ALL OVER THE DOUGH.\r\n\r\n",
    "WATCH OUT.\r\n\r\n",
    "AND THEN WE PUT\r\nTHE CINNAMON, BROWN SUGAR.\r\n\r\n",
    "THAT IS A TON\r\n   OF CINNAMON AND SUGAR.\r\nIT IS.\r\n\r\n",
    "WHAT KIND OF NUTS?\r\nPECANS.\r\n\r\n",
    "THEN WE'RE GONNA ROLL IT\r\n   FROM THE FREE.\r\n\r\n",
    "SERRATED\r\nSO IT DOESN'T TEAR.\r\n\r\n",
    "DO THEY GO RIGHT\r\n     IN THE CENTER?\r\nUM, THAT'S FINE.\r\n\r\n",
    "HEAVY.\r\n\r\n",
    "WHAT PART DO YOU EAT FIRST--\r\n  THE CENTER OR THE OUTSIDE?\r\nTHE CENTER.\r\n\r\n",
    "THAT'S WHERE YOU GO?\r\nYEAH.\r\n\r\n",
    "MY SON HUNTER WOULD GO--\r\n    OR RYDER--\r\n\r\n",
    "WOULD GO OUT\r\n  OF THEIR MINDS FOR THIS.\r\n\r\n",
    "AS A MATTER OF FACT,\r\n I GOTTA TAKE HIM ONE OF THESE.\r\n\r\n",
    "GET A SPATULA, TOO.\r\nSPATULA? OKAY.\r\n\r\n",
    "YEAH, YOU'RE GONNA HAVE\r\n TO SCRAPE ME OFF THE CEILING\r\n\r\n",
    "AFTER THIS MUCH SUGAR.\r\n\r\n",
    "I'M GOOD FOR TWO\r\n    A DAY SOMETIMES.\r\nTWO A DAY?\r\n\r\n",
    "ONE IN THE MORNING\r\n     AND THEN--\r\n YOU NEED TO GET\r\nINTO SOME REHAB, BRO.\r\n\r\n",
    "WE NEED TO HAVE\r\nA COUNSEL GROUP.\r\n  THAT'S THE WHOLE REASON\r\n  I HAVEN'T LEFT THIS TOWN\r\n\r\n",
    "IS BECAUSE\r\n   OF THE CINNAMON ROLLS.\r\n\r\n",
    "<i> SONJA'S SURE NOT</i>\r\n  <i> GOING ANYWHERE.</i>\r\n\r\n",
    "<i> SHE'S HAVING TOO MUCH FUN...</i>\r\n\r\n",
    "SHE STACKED HER EGGSHELLS.\r\n\r\n",
    "<i> RUNNING THE PLACE TO GO...</i>\r\n\r\n",
    "DID HE PUT HIS HAIR ON FOR ME?\r\n  IS THAT FOR ME TODAY?\r\nYEAH, FOR YOU.\r\n\r\n",
    "YOU'RE MONEY.\r\n\r\n",
    "<i> IN HER HOMETOWN.</i>\r\n\r\n",
    "ASK ME WHAT\r\n    I GET FOR DINNER?\r\n I DON'T KNOW\r\nCINNAMON ROLL KING.\r\n\r\n",
    "EXACTLY,\r\n    A CINNAMON ROLL.\r\n NO, YOU DON'T GET\r\nA CINNAMON ROLL FOR--\r\n\r\n",
    "YES, I DO.\r\n\r\n",
    "WELL, THAT'S IT FOR THIS TRIP,\r\n  BUT DON'T WORRY.\r\n\r\n",
    "I'LL BE LOOKIN' FOR YA\r\n\r\n",
    "AT AMERICA'S GREATEST DINERS,\r\n  DRIVE-INS AND DIVES.\r\n\r\n",
    "NOW THAT PUTS\r\n    THE \"T\" IN TASTY.\r\n\r\n",
    "THAT MADE NO SENSE.\r\n\r\n"
  ]
}
